services:
  victoria-db:
    image: postgres:15-alpine
    container_name: victoria-db-local
    environment:
      - POSTGRES_DB=victoria_wms
      - POSTGRES_USER=vicky_admin
      - POSTGRES_PASSWORD=vicky_password
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U vicky_admin -d victoria_wms" ]
      interval: 5s
      timeout: 5s
      retries: 5

  victoria-cache:
    image: redis:alpine
    container_name: victoria-cache-local
    ports:
      - "6379:6379"
