name: victoria_mobile
description: Victoria WMS Core Mobile Client.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Networking
  dio: ^5.4.0
  
  # State Management
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  
  # Utils
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

  # Hardware Preparation (Fase 5 Req)
  flutter_blue_plus: ^1.30.0 # Bluetooth
  sqflite: ^2.3.0 # Local Config/Storage
  flutter_bloc: ^9.1.1
  flutter_secure_storage: ^10.0.0
  vibration: ^3.1.5
  audioplayers: ^6.5.1
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  build_runner: ^2.4.8
  riverpod_generator: ^2.3.9
  freezed: ^2.4.6
  json_serializable: ^6.7.1
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
